// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/services/program.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	exec "os/exec"
	reflect "reflect"
)

// MockProgramService is a mock of ProgramService interface
type MockProgramService struct {
	ctrl     *gomock.Controller
	recorder *MockProgramServiceMockRecorder
}

// MockProgramServiceMockRecorder is the mock recorder for MockProgramService
type MockProgramServiceMockRecorder struct {
	mock *MockProgramService
}

// NewMockProgramService creates a new mock instance
func NewMockProgramService(ctrl *gomock.Controller) *MockProgramService {
	mock := &MockProgramService{ctrl: ctrl}
	mock.recorder = &MockProgramServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProgramService) EXPECT() *MockProgramServiceMockRecorder {
	return m.recorder
}

// Compile mocks base method
func (m *MockProgramService) Compile(ctx context.Context, sourceRelativePath, binaryRelativePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, sourceRelativePath, binaryRelativePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compile indicates an expected call of Compile
func (mr *MockProgramServiceMockRecorder) Compile(ctx, sourceRelativePath, binaryRelativePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockProgramService)(nil).Compile), ctx, sourceRelativePath, binaryRelativePath)
}

// GetExecutionCommand mocks base method
func (m *MockProgramService) GetExecutionCommand(ctx context.Context, sourceRelativePath, binaryRelativePath string) *exec.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionCommand", ctx, sourceRelativePath, binaryRelativePath)
	ret0, _ := ret[0].(*exec.Cmd)
	return ret0
}

// GetExecutionCommand indicates an expected call of GetExecutionCommand
func (mr *MockProgramServiceMockRecorder) GetExecutionCommand(ctx, sourceRelativePath, binaryRelativePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionCommand", reflect.TypeOf((*MockProgramService)(nil).GetExecutionCommand), ctx, sourceRelativePath, binaryRelativePath)
}

// GetSourceFileExtension mocks base method
func (m *MockProgramService) GetSourceFileExtension() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceFileExtension")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSourceFileExtension indicates an expected call of GetSourceFileExtension
func (mr *MockProgramServiceMockRecorder) GetSourceFileExtension() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceFileExtension", reflect.TypeOf((*MockProgramService)(nil).GetSourceFileExtension))
}

// GetBinaryFileExtension mocks base method
func (m *MockProgramService) GetBinaryFileExtension() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinaryFileExtension")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBinaryFileExtension indicates an expected call of GetBinaryFileExtension
func (mr *MockProgramServiceMockRecorder) GetBinaryFileExtension() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinaryFileExtension", reflect.TypeOf((*MockProgramService)(nil).GetBinaryFileExtension))
}

// MockProgramServiceRuntime is a mock of ProgramServiceRuntime interface
type MockProgramServiceRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockProgramServiceRuntimeMockRecorder
}

// MockProgramServiceRuntimeMockRecorder is the mock recorder for MockProgramServiceRuntime
type MockProgramServiceRuntimeMockRecorder struct {
	mock *MockProgramServiceRuntime
}

// NewMockProgramServiceRuntime creates a new mock instance
func NewMockProgramServiceRuntime(ctrl *gomock.Controller) *MockProgramServiceRuntime {
	mock := &MockProgramServiceRuntime{ctrl: ctrl}
	mock.recorder = &MockProgramServiceRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProgramServiceRuntime) EXPECT() *MockProgramServiceRuntimeMockRecorder {
	return m.recorder
}

// RunCommand mocks base method
func (m *MockProgramServiceRuntime) RunCommand(cmd *exec.Cmd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunCommand", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunCommand indicates an expected call of RunCommand
func (mr *MockProgramServiceRuntimeMockRecorder) RunCommand(cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCommand", reflect.TypeOf((*MockProgramServiceRuntime)(nil).RunCommand), cmd)
}
